name: instagramhomework
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_staggered_grid_view: ^0.6.1
  font_awesome_flutter: ^10.1.0

  # for firebase
  firebase_core: ^1.13.1 
  firebase_auth: ^3.3.9 
  firebase_storage: ^10.2.9
  cloud_firestore: ^3.1.10

  # for image
  image_picker: ^0.8.4+11
  cached_network_image: ^3.2.0

  shared_preferences: ^2.0.13
  logger: ^1.1.0

  intl: ^0.17.0
  
  get: ^4.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong.ttf

